# Generated by Django 5.2.1 on 2025-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('campaign', models.CharField(blank=True, null=True)),
                ('chain', models.CharField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('extraction', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('client_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('address_1', models.CharField(blank=True, null=True)),
                ('address_2', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('campaign_code', models.CharField(blank=True, null=True)),
                ('chain_code', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketing',
                'managed': False,
            },
        ),
    ]
