# Generated by Django 5.2.1 on 2025-06-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('sequence_no', models.IntegerField()),
            ],
            options={
                'db_table': 'plan_mapping',
                'managed': False,
            },
        ),
    ]
