# Generated by Django 5.2.1 on 2025-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_planmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(blank=True, null=True)),
                ('chain_code', models.CharField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('price', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_products',
                'managed': False,
            },
        ),
    ]
