# Generated by Django 5.2.1 on 2025-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_campaignproduct_delete_campaignproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, null=True)),
                ('chain_code', models.CharField(blank=True, null=True)),
                ('campaign_code', models.CharField(blank=True, null=True)),
                ('total_amount_entered', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('check1_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('check1_number', models.CharField(blank=True, null=True)),
                ('check2_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('check2_number', models.CharField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, null=True)),
                ('total_cash_eur', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total_checks_eur', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total_card_eur', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('number_of_invoices_paid', models.IntegerField(blank=True, null=True)),
                ('final_total_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'payment_details',
                'managed': False,
            },
        ),
    ]
