# Generated by Django 5.2.1 on 2025-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_salesdump'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.CharField(max_length=50)),
                ('marketing_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('sequence_no', models.IntegerField()),
            ],
            options={
                'db_table': 'marketing_plan',
            },
        ),
    ]
