# Generated by Django 5.2.1 on 2025-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_marketingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProducts',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('campaign_code', models.CharField(blank=True, null=True)),
                ('chain_name', models.CharField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('price', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CampaignProduct',
        ),
    ]
